// English translations
export const en = {
  // Common
  common: {
    appName: 'Million Questions AI',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
  },

  // Home Page
  home: {
    logo: '💡',
    title: 'A good question is worth a million.',
    subtitle: 'Great products start with great questions.',
    exploreButton: 'Explore Possibilities',
  },

  // Inspiration Page
  inspiration: {
    title: 'Explore Possibilities',
    header: 'A good question is worth a million.',
    subtitle: 'Here, present your challenge, and we will reveal opportunities for you.',
    placeholder: 'For example: How to create a phenomenal learning product for the next generation?',
    generateButton: 'Generate Golden Question List',
    boardButton: 'Convene Virtual Board',
    inputRequired: 'Please enter your question or idea',
  },

  // Questions Page
  questions: {
    title: 'Golden Question List',
    generatedBy: 'Generated by Chief Strategy Officer',
    loadingMessages: {
      summoning: 'Summoning Chief Strategic Analyst...',
      analyzing: 'Deep analysis of your idea, distilling core insights...',
      crafting: 'Master Questioner is crafting tailored questions...',
      organizing: 'Organizing question list...',
      completing: 'Completing personalized question list...',
    },
    seekSolution: 'Seek Solution',
    noIdea: 'Please enter your idea first',
  },

  // Mentor Hall Page
  mentorHall: {
    title: 'Master Hall',
    subtitle: 'Converse with a master to seek wisdom for your question',
    loadingMessages: {
      analyzing: 'Analyzing the core of your question, connecting AI wisdom network...',
      understanding: 'AI is deeply understanding the essence of your question...',
      calculating: 'Calculating mentor compatibility...',
      locking: 'Destined mentor locked! Establishing exclusive connection...',
    },
    aiRecommendation: 'AI Recommendation',
    aiRecommendationSubtitle: 'Based on your question, we believe this mentor is the best match',
    recommendedBadge: 'AI Pick',
    masterGallery: 'Master Gallery',
    masterGallerySubtitle: 'You can also choose other mentors',
    consultButton: 'Consult Them',
    selectMentorFirst: 'Please select a mentor first',
    selectQuestionFirst: 'Please select a question first',
  },

  // Solution Page
  solution: {
    title: 'Wisdom Solution',
    generatedBy: 'Generated by',
    loadingMessages: {
      connecting: 'Establishing deep connection with master...',
      analyzing: 'Analyzing your question deeply...',
      crafting: 'Crafting personalized solution...',
      polishing: 'Polishing solution details...',
      completing: 'Completing wisdom dialogue...',
    },
    backToQuestions: 'Back to Questions',
    noQuestion: 'Please select a question first',
  },

  // Board Report Page
  boardReport: {
    title: 'Board Report',
    generatedBy: 'Generated by Virtual Board',
    loadingMessages: {
      convening: 'Convening virtual board meeting...',
      navigatorAnalyzing: 'Navigator is conducting core analysis...',
      membersDiscussing: 'Board members are discussing from various perspectives...',
      synthesizing: 'Synthesizing board opinions, generating decision...',
      completing: 'Completing board report...',
    },
    navigatorSection: 'Navigator Analysis',
    membersSection: 'Board Members Opinions',
    conclusionSection: 'Board Conclusion',
    backToInspiration: 'Back to Inspiration',
    noIdea: 'Please enter your idea first',
  },

  // Board Selection Modal
  boardSelection: {
    step1Title: 'Step 1: Select a "Navigator"',
    step1Subtitle: 'They will provide you with the first core analysis report',
    step2Title: 'Step 2: Select Board Members (Multiple)',
    step2Subtitle: 'They will examine your idea from different perspectives',
    styleRep: 'Style Representative',
    expertise: 'Expertise',
    prevButton: 'Previous',
    nextButton: 'Next',
    generateButton: 'Generate Board Decision',
    selectNavigatorFirst: 'Please select a navigator first',
    selectMemberFirst: 'Please select at least one board member',
  },

  // Mentors
  mentors: {
    visionary: {
      name: 'Visionary Founder',
      philosophy: 'Obsessed with product soul and emotional resonance with users',
    },
    hacker: {
      name: 'Growth Hacker',
      philosophy: 'Drive growth with data, break through with innovation',
    },
    cfo: {
      name: 'Chief Financial Officer',
      philosophy: 'Numbers reveal the truth of business',
    },
    scientist: {
      name: 'Data Scientist',
      philosophy: 'Let data speak, let science decide',
    },
    doer: {
      name: 'Executor',
      philosophy: 'Actions speak louder than words, results prove everything',
    },
    strategist: {
      name: 'Chief Strategy Officer',
      philosophy: 'Strategy determines direction, execution determines success',
    },
    innovator: {
      name: 'Innovator',
      philosophy: 'Breaking conventions, creating new paradigms',
    },
    pragmatist: {
      name: 'Pragmatist',
      philosophy: 'Practical execution, results-oriented',
    },
    humanist: {
      name: 'Humanist',
      philosophy: 'User-centered, empathy-driven',
    },
  },

  // Board Roles
  boardRoles: {
    navigators: {
      product: {
        name: 'Product Thinker',
        representative: 'Steve Jobs',
        quote: '"Innovation distinguishes between a leader and a follower."',
      },
      strategy: {
        name: 'Strategic Thinker',
        representative: 'Andy Grove',
        quote: '"Only the paranoid survive."',
      },
      design: {
        name: 'Design Thinker',
        representative: 'Don Norman',
        quote: '"Good design is actually harder to notice than poor design."',
      },
    },
    members: {
      technical: {
        name: 'Technical Expert',
        expertise: 'Technology feasibility, architecture design',
      },
      marketing: {
        name: 'Marketing Expert',
        expertise: 'Market positioning, user acquisition',
      },
      operations: {
        name: 'Operations Expert',
        expertise: 'Operational efficiency, growth strategy',
      },
      finance: {
        name: 'Finance Expert',
        expertise: 'Business model, revenue structure',
      },
      user: {
        name: 'User Experience Expert',
        expertise: 'User needs, experience design',
      },
      innovation: {
        name: 'Innovation Expert',
        expertise: 'Innovative thinking, paradigm shift',
      },
    },
  },

  // Share
  share: {
    title: 'Share Image',
    saveButton: 'Save to Album',
    shareButton: 'Share',
    closeButton: 'Close',
    saveSuccess: 'Image saved successfully',
    saveFailed: 'Failed to save image',
  },
};
